__title__ = 'grabstats'
__description__ = 'Scrape NBA stats from Basketball-Reference'
__url__ = 'https://github.com/kndo/grabstats'
__version__ = '0.1.0'
__author__ = 'Khanh Do'
__author_email__ = 'dokhanh@gmail.com'
__license__ = 'MIT License'
